spring:
  application:
    name: tourism-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tourism_management
    username: root
    password: wyjh030208..    # mac
#    password: 123456    # win
  data:
    # redis
    redis:
      host: 127.0.0.1    # redis 主机
      port: 6379        # redis 端口号
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 8
          min-idle: 0
      timeout: 0
server:
  port: 8080
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0


