package com.yannqing.template.common;

/** TODO 需要优化：两个枚举不合适
 * @description: 权限相关常量
 * @author: yannqing
 * @create: 2025-01-17 17:20
 **/
public interface PermissionConstant {
    String USER_AUTH = "USER_AUTH";
    String USER_MANAGEMENT = "USER_MANAGEMENT";
    String ROLE_MANAGEMENT = "ROLE_MANAGEMENT";
    String PERMISSION_MANAGEMENT = "PERMISSION_MANAGEMENT";
    String AUTH_LOGIN = "USER_LOGIN";
    String AUTH_REGISTER = "USER_REGISTER";
    String AUTH_LOGOUT = "AUTH_LOGOUT";
    String USER_GET_ALL = "USER_GET_ALL";
    String USER_ADD = "USER_ADD";
    String USER_UPDATE_MYSELF = "USER_UPDATE_MYSELF";
    String USER_UPDATE_USER_INFO = "USER_UPDATE_USER_INFO";
    String USER_UPDATE_MYSELF_PASSWORD = "USER_UPDATE_MYSELF_PASSWORD";
    String USER_RESET_PASSWORD = "USER_RESET_PASSWORD";
    String USER_EXPORT = "USER_EXPORT";
    String USER_ADD_ROLE_TO_USER = "USER_ADD_ROLE_TO_USER";
    String USER_GET_ONE = "USER_GET_ONE";
    String USER_DELETE_ONE = "USER_DELETE_ONE";
    String USER_GET_ROLE_BY_USER = "USER_GET_ROLE_BY_USER";
    String USER_DELETE_BATCH = "USER_DELETE_BATCH";
    String ROLE_GET_ALL = "ROLE_GET_ALL";
    String ROLE_ADD = "ROLE_ADD";
    String ROLE_UPDATE = "ROLE_UPDATE";
    String ROLE_ADD_PERMISSION_TO_ROLE = "ROLE_ADD_PERMISSION_TO_ROLE";
    String ROLE_GET_PERMISSION = "ROLE_GET_PERMISSION";
    String ROLE_DELETE_ONE = "ROLE_DELETE_ONE";
    String ROLE_DELETE_BATCH = "ROLE_DELETE_BATCH";
    String PERMISSION_GET_ALL = "PERMISSION_GET_ALL";
    String PERMISSION_ADD = "PERMISSION_ADD";
    String PERMISSION_UPDATE = "PERMISSION_UPDATE";
    String PERMISSION_DELETE_ONE = "PERMISSION_DELETE_ONE";
    String PERMISSION_DELETE_BATCH = "PERMISSION_DELETE_BATCH";
    String USER_GET_PERMISSION_BY_USER = "USER_GET_PERMISSION_BY_USER";
    String USER_GET_MYSELF_INFO = "USER_GET_MYSELF_INFO";

}
